# Generated by Django 5.2.1 on 2025-05-23 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('saga', models.CharField(blank=True, max_length=150)),
                ('start_episode', models.PositiveIntegerField()),
                ('end_episode', models.PositiveIntegerField()),
                ('summary', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DevilFruitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArcRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rank_position', models.PositiveIntegerField()),
                ('ranked_by', models.CharField(max_length=150)),
                ('arc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.arc')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArcRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('reviewer', models.CharField(max_length=100)),
                ('arc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='dashboard.arc')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DevilFruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('current_user', models.CharField(blank=True, max_length=150, null=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.devilfruittype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
